let correctCount = 0;

const questionBank = [
	{
		questionNumber: 1,
		question: 'Your goldfish came back with black marks on his scales. What are they?',
		a: 'Ammonia burns from chemical buildup in the water',
		b: 'Dead scales resulting from fish fights',
		c: 'Fungus colonies growing on the goldfish',
		d: 'Nothing to worry about, probably result of crossbreeding black goldfish',
		correctAns: 'Ammonia burns from chemical buildup in the water',
		emoji: 'https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/fire_1f525.png',
		alt: 'Fire emoji',
	},
	{
		questionNumber: 2,
		question: 'Experts note that you should not keep goldfish in traditional fish bowls. Why?',
		a: 'The fish bowl\'s round shape confuses goldfish and causes them to hit their heads',
		b: 'The fish bowl\'s round shape allows for faster bacteria growth',
		c: 'Goldfish prefer taller tanks, where they can swim vertically',
		d: 'Fish bowls are generally too small for goldfish to thrive in',
		correctAns: 'Fish bowls are generally too small for goldfish to thrive in',
		emoji: 'https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/fishing-pole-and-fish_1f3a3.png',
		alt: 'Fishing pole emoji',
	},
	{
		questionNumber: 3,
		question: 'Since you\'re not going to get a fish bowl, what is the ideal tank size for a common goldfish?',
		a: '5 gallons',
		b: '15 gallons',
		c: 'Nothing greater than 30 gallons',
		d: '30 gallons or more',
		correctAns: '30 gallons or more',
		emoji: 'https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/potable-water-symbol_1f6b0.png',
		alt: 'Potable water emoji',
	},
	{
		questionNumber: 4,
		question: 'Why do goldfish need so much space? How big can the common goldfish grow, anyway?',
		a: 'Typically, up to 4 inches long',
		b: 'Typically, up to 7-8 inches long',
		c: 'Typically, up to 12 inches long',
		d: 'Goldfish grow to a maximum of 3 feet long',
		correctAns: 'Typically, up to 12 inches long',
		bonusFact: 'Some goldfish hobbyists have reported common goldfish as large as 18 inches long! (Source: http://animal-world.com/encyclo/fresh/goldfish/CommonGoldfish.php)',
		emoji: 'https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/straight-ruler_1f4cf.png',
		alt: 'Ruler emoji',
	},
	{
		questionNumber: 5,
		question: 'It\'s best to get goldfish tanks with lids because...',
		a: 'Tank lids keep the good filtered oxygen in, and bad oxygen out',
		b: 'Goldfish are known to jump out of their tanks',
		c: 'Household insects can carry harmful bacteria to aquariums',
		d: 'Lids prevent tank water from evaporating',
		correctAns: 'Goldfish are known to jump out of their tanks',
		emoji: 'https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/top-hat_1f3a9.png',
		alt: 'Top hat emoji',
	},
	{
		questionNumber: 6,
		question: 'Which of the following is the best feeding schedule for your goldfish?',
		a: 'Feed your fish once in the morning, but give it enough food for 5 minutes of eating',
		b: 'Schedules can vary from 2-5x a day, but feed them only for 1-2 minutes',
		c: 'Goldfish only need to be fed once every other day',
		d: 'Goldfish only need to be fed once a week',
		correctAns: 'Schedules can vary from 2-5x a day, but feed them only for 1-2 minutes',
		emoji: 'https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/81/fork-and-knife-with-plate_1f37d.png',
		alt: 'Fork and knife emoji',
	},
	{
		questionNumber: 7,
		question: 'What temperatures do goldfish like to live in?',
		a: 'A wide range from 40\xB0 - 60\xB0 F',
		b: 'A static temperature between 65\xB0 - 75\xB0 F',
		c: 'A wide range from 50\xB0 - 75\xB0 F',
		d: 'Within the narrow range of 75\xB0 - 80\xB0 F',
		correctAns: 'A wide range from 50\xB0 - 75\xB0 F',
		emoji: 'https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/thermometer_1f321.png',
		alt: 'Thermometer emoji',
	},
	{
		questionNumber: 8,
		question: 'At about what age can you reliably know what gender your goldfish is?',
		a: '3 months',
		b: '6 months',
		c: '1 year',
		d: '2 years',
		correctAns: '1 year',
		emoji: 'https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/female-sleuth-type-1-2_1f575-1f3fb-200d-2640-fe0f.png',
		alt: 'Woman detective emoji',
	},
	{
		questionNumber: 9,
		question: 'About how long did the oldest goldfish live?',
		a: '15 years',
		b: '28 years',
		c: '31 years',
		d: '43 years',
		correctAns: '43 years',
		bonusFact: 'The world\'s oldest captive goldfish lived for (at least) 43 years. (Source: http://news.bbc.co.uk/2/hi/uk/414114.stm)',
		emoji: 'https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/wilted-flower_1f940.png',
		alt: 'Wilted flower emoji',
	},
	{
		questionNumber: 10,
		question: 'Bonus question: In one study conducted by Keio University, goldfish were taught to:',
		a: 'Jump out of the water whenever a researcher clapped 3 times',
		b: 'Distinguish between the music of two classical composers',
		c: 'Play dead when \"too much food\" was dropped into the tank',
		d: 'Fight one another when LED lights on the tank flashed on and off',
		correctAns: 'Distinguish between the music of two classical composers',
		emoji: 'https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/musical-note_1f3b5.png',
		alt: 'Music note emoji',
	}
]